Sprint 04
DanteIT94/MovieQuizApp pull request #2
Opened 2023-01-11 12:39 UTC by DanteIT94

In accordance with specification of Yandex Practicum (Sprint № 4):
1) Launch Screen (identical to the layout in Figma);
2) The main screen of the application, identical to the layouts in Figma, with the implemented logic.

2023-01-12 10:37 UTC, IBDesignable requested changes

2023-01-12 10:37 UTC, IBDesignable commented on MovieQuiz/Helpers/UIColor+Extensions.swift
> +    static let YPBlack = UIColor(red: 26/255, green: 27/255, blue: 34/255, alpha: 1)
Лучше использовать цвета из ассетов (они же туда зачем-то добавлены), инициализатор с парамтером named

2023-01-12 10:37 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet weak var noButton: UIButton!
private

2023-01-12 10:37 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        yesButton.transform = CGAffineTransform(scaleX: 0.9, y: 0.9)
давай поправим форматриование: cmd+a и control+i 

Также, договоримся, что между логическими блоками будем оставлять одну пустую строчку

2023-01-12 10:37 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        let action = UIAlertAction(title: result.buttonText, style: .default, handler: { _ in self.currentQuestionIndex = 0
здесь принято начинать с новой строки
```suggestion
        let action = UIAlertAction(title: result.buttonText, style: .default, handler: { _ in 
            self.currentQuestionIndex = 0
```

2023-01-12 10:37 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageLabel.layer.cornerRadius = 6 // радиус скругления углов рамки
не по макету

Это свойство можно настроить один раз: на сториборде или во viewDidLoad

2023-01-12 10:37 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageLabel.layer.masksToBounds = true // даём разрешение на рисование рамки
аналогично, это свойство достаточно настроить один раз

2023-01-12 10:37 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private func showNextQuestionOrResult() {
давай здесь и далее добавим отбивку одной пустой строкой

2023-01-12 10:37 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @objc func yesButtonPressed() {
private

2023-01-12 10:37 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +
давай договоримся, что на ревью закомменченный код не будем отправлять. Это мертвый код, который не нужен :)

2023-01-12 14:04 UTC, DanteIT94 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +
Огромное спасибо! Возможно, пропустил когда делал финальный чек-ап)

2023-01-12 17:07 UTC, DanteIT94 commented on MovieQuiz/Helpers/UIColor+Extensions.swift
> +    static let YPBlack = UIColor(red: 26/255, green: 27/255, blue: 34/255, alpha: 1)
Сделано, спасибо за подсказку)

2023-01-12 17:10 UTC, DanteIT94 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet weak var noButton: UIButton!
Исправлено!

2023-01-12 17:12 UTC, DanteIT94 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        yesButton.transform = CGAffineTransform(scaleX: 0.9, y: 0.9)
Прошу Вас уточнить, а что такое "Логический блок" в коде?

2023-01-12 17:13 UTC, DanteIT94 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        let action = UIAlertAction(title: result.buttonText, style: .default, handler: { _ in self.currentQuestionIndex = 0
Исправлено!

2023-01-13 10:42 UTC, DanteIT94 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private func showNextQuestionOrResult() {
Не понимаю, что это значит)

2023-01-15 11:44 UTC, DanteIT94 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @objc func yesButtonPressed() {
Сделано

2023-01-15 12:15 UTC, DanteIT94 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageLabel.layer.cornerRadius = 6 // радиус скругления углов рамки
Исправил на imageLabel.layer.cornerRadius = 20 (как в макете)

2023-01-15 12:15 UTC, DanteIT94 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageLabel.layer.masksToBounds = true // даём разрешение на рисование рамки
Принято

2023-01-15 18:38 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        yesButton.transform = CGAffineTransform(scaleX: 0.9, y: 0.9)
Денис, под логическим блоком я имею ввиду функции, классы и структуры, расширения классов. Также ты можешь написать одну очень большую функцию, но явно отделить шаги алгоритма пустыми строками. 

Это все не влияет на решение задачи в спринте, однако аккуратное ведение кода очень пригодится на работе 👍🏻

спасибо что уточнил, буду четче формулировать это выражение)

2023-01-15 18:39 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private func showNextQuestionOrResult() {
Здесь как в предыдущем комменатрии конец одной функции и начало другой слипаются. Обычно принято оставлять немного пустого пространство, чтобы при беглом чтении кода можно было быстро соориентироваться

2023-01-15 19:32 UTC, DanteIT94 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        yesButton.transform = CGAffineTransform(scaleX: 0.9, y: 0.9)
Понял, принял! Огромное спасибо за разъяснение!)

2023-01-15 19:32 UTC, DanteIT94 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private func showNextQuestionOrResult() {
Понял)

2023-01-15 19:51 UTC, merged